import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_callkit_incoming/flutter_callkit_incoming.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'dart:async';

import 'package:flutter_callkit_incoming/entities/entities.dart'; // Import Event enum
import 'package:vc/screens/user_registration_screen.dart'; // Corrected import
import 'package:vc/screens/call_screen.dart'; // Corrected import
import 'package:vc/services/notification_service.dart'; // Corrected import
import 'package:vc/services/permissions_service.dart'; // Corrected import


final GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

// Tracks processed CallKit IDs to prevent duplicate UI/actions
Set<String> processedCallKitIds = {}; // Changed to public
Timer? _callAcceptanceTimer; // Debounces ACTION_CALL_ACCEPT events

/// Entry point
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await PermissionsService.requestAllPermissions();

  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  setupCallkitListeners();

  runApp(const MyApp());

  // Post-launch cold-start navigation from SharedPreferences
  WidgetsBinding.instance.addPostFrameCallback((_) async {
    final prefs = await SharedPreferences.getInstance();
    final pendingCallChannelId = prefs.getString('pendingCallChannelId');
    if (pendingCallChannelId != null) {
      debugPrint('DEBUG: App started with pending call. Navigating to CallScreen for channel: $pendingCallChannelId');
      await prefs.remove('pendingCallChannelId'); // Clear immediately
      _navigateToCallScreen(pendingCallChannelId);
    }
  });
}

void _navigateToCallScreen(String channelId) {
  if (navigatorKey.currentState != null && navigatorKey.currentState!.mounted) {
    bool alreadyOnCallScreen = false;
    navigatorKey.currentState?.popUntil((route) {
      if (route is MaterialPageRoute &&
          route.settings.name == '/callScreen' &&
          route.settings.arguments != null &&
          route.settings.arguments is Map &&
          (route.settings.arguments as Map)['channelId'] == channelId) {
        alreadyOnCallScreen = true;
      }
      return true; // Keep popping to ensure the check covers the stack
    });

    if (!alreadyOnCallScreen) {
      debugPrint('DEBUG: Pushing CallScreen for channel: $channelId');
      navigatorKey.currentState?.pushReplacement( // Use pushReplacement to avoid stacking
        MaterialPageRoute(
          builder: (_) => CallScreen(uid: 0, channelId: channelId),
          settings: RouteSettings(name: '/callScreen', arguments: {'channelId': channelId}),
        ),
      );
    } else {
      debugPrint('DEBUG: Already on CallScreen for channel $channelId. Not navigating again.');
    }
  } else {
    debugPrint('DEBUG: Navigator not ready to navigate to CallScreen.');
  }
}


/// Listen to CallKit events (Accept/Decline)
void setupCallkitListeners() {
  FlutterCallkitIncoming.onEvent.listen((event) async {
    final Event? eventType = event?.event;
    final body = event?.body;
    final callkitId = body?['id']; // This is the UUID generated by CallKit/plugin

    debugPrint('CallKit Event Received: ${eventType.toString()}, ID: $callkitId, Body: $body');
    debugPrint('DEBUG: eventType value (enum.toString()): "${eventType.toString()}"');
    debugPrint('DEBUG: eventType type: ${eventType.runtimeType}');


    if (callkitId == null) {
      debugPrint('DEBUG: CallKit event received with null ID. Skipping processing.');
      return;
    }

    switch (eventType) {
      case Event.actionCallIncoming:
        // This event signifies CallKit's internal handling, not the initial app-driven display.
        // The display debounce is now handled in LocalNotificationService.showIncomingCallNotification.
        // We still add to processedCallKitIds here to ensure that *this* event is considered processed
        // for subsequent logic, but it's not the primary gate for the visual notification.
        if (!processedCallKitIds.contains(callkitId)) { // Updated variable name
          // This case might happen if CallKit processes an incoming call *before* our FCM listener.
          // In such rare cases, we still want to record the ID.
          processedCallKitIds.add(callkitId); // Updated variable name
          debugPrint('DEBUG: ACTION_CALL_INCOMING event received for new ID: $callkitId. Marking as processed.');
        } else {
          debugPrint('DEBUG: Skipping duplicate ACTION_CALL_INCOMING event for ID: $callkitId. Already processed.');
        }
        break; 

      case Event.actionCallAccept:
        if (_callAcceptanceTimer != null && _callAcceptanceTimer!.isActive) {
          debugPrint('DEBUG: Call ACCEPT debounce active. Skipping duplicate accept event for ID: $callkitId');
          return;
        }

        _callAcceptanceTimer = Timer(const Duration(milliseconds: 500), () async {
          debugPrint('DEBUG: Call ACCEPT timer triggered for ID: $callkitId');
          final channelId = body?['extra']?['channelId'];
          if (channelId != null) {
            final prefs = await SharedPreferences.getInstance();
            await prefs.setString('pendingCallChannelId', channelId); // Store for cold-start resilience

            _navigateToCallScreen(channelId); // Trigger navigation to CallScreen
            await prefs.remove('pendingCallChannelId'); // Clear after navigation attempt
          } else {
            debugPrint('ERROR: ACTION_CALL_ACCEPT event missing channelId.');
          }
          processedCallKitIds.remove(callkitId); // Updated variable name
          _callAcceptanceTimer = null; // Clear the timer
        });
        break;

      case Event.actionCallDecline:
      case Event.actionCallEnded:
      case Event.actionCallTimeout:
        final callId = body?['id'];
        if (callId != null) {
          debugPrint('CallKit ACTION_CALL_DECLINE/ENDED/TIMEOUT for ID: $callId');
          await FlutterCallkitIncoming.endCall(callId);
          final prefs = await SharedPreferences.getInstance();
          await prefs.remove('pendingCallChannelId'); // Clear any pending call
          processedCallKitIds.remove(callId); // Updated variable name
          _callAcceptanceTimer?.cancel(); // Cancel any pending accept timers
          _callAcceptanceTimer = null;
        }
        break;

      default:
        debugPrint('DEBUG: Unhandled CallKit Event Type: ${eventType.toString()}');
        break;
    }
  });

  // This listener processes incoming FCM messages while the app is in the foreground.
  FirebaseMessaging.onMessage.listen((RemoteMessage message) {
    debugPrint('FCM Received (Foreground): ${message.data}');
    final callerId = message.data['callerId'];
    final channelId = message.data['channelId'];
    final fcmCallKitId = message.data['callkitId']; // Get CallKit ID from FCM

    // Debounce FCM: Only show CallKit UI if we haven't already processed this CallKit ID.
    // This handles scenarios where multiple FCMs for the *same* CallKit ID might arrive.
    if (fcmCallKitId != null && processedCallKitIds.contains(fcmCallKitId)) { // Updated variable name
        debugPrint('DEBUG: FCM for already processed CallKit ID: $fcmCallKitId. Skipping visual notification.');
        return;
    }

    if (callerId != null && channelId != null) {
      // Show the CallKit incoming UI, passing the consistent CallKit ID.
      LocalNotificationService.showIncomingCallNotification(callerId, channelId, incomingCallkitId: fcmCallKitId);
    }
  });
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Video Call App',
      navigatorKey: navigatorKey,
      theme: ThemeData.dark(),
      debugShowCheckedModeBanner: false,
      home: const UserRegistrationScreen(),
    );
  }
}